import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

final appTheme = TextTheme(
  headline1: GoogleFonts.russoOne(
      fontSize: 97,
      fontWeight: FontWeight.w300,
      letterSpacing: -1.5,
      color: Colors.white),
  headline2: GoogleFonts.russoOne(
      fontSize: 61,
      fontWeight: FontWeight.w300,
      letterSpacing: -0.5,
      color: Colors.white),
  headline3: GoogleFonts.russoOne(fontSize: 48, fontWeight: FontWeight.w400),
  headline4: GoogleFonts.russoOne(
      fontSize: 34,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.25,
      color: Colors.white),
  headline5: GoogleFonts.russoOne(
      fontSize: 24, fontWeight: FontWeight.w400, color: Colors.white),
  headline6: GoogleFonts.russoOne(
      fontSize: 20,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.15,
      color: Colors.white),
  subtitle1: GoogleFonts.russoOne(
      fontSize: 16,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.15,
      color: Colors.white),
  subtitle2: GoogleFonts.russoOne(
      fontSize: 14,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.1,
      color: Colors.white),
  bodyText1: GoogleFonts.russoOne(
      fontSize: 16,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.5,
      color: Colors.white),
  bodyText2: GoogleFonts.russoOne(
      fontSize: 14,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.25,
      color: Colors.white),
  button: GoogleFonts.russoOne(
      fontSize: 14,
      fontWeight: FontWeight.w500,
      letterSpacing: 1.25,
      color: Colors.white),
  caption: GoogleFonts.russoOne(
      fontSize: 12,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.4,
      color: Colors.white),
  overline: GoogleFonts.russoOne(
      fontSize: 10,
      fontWeight: FontWeight.w400,
      letterSpacing: 1.5,
      color: Colors.white),
);
